# Generated by Django 2.1.7 on 2019-03-11 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EspecificacionProducto',
            fields=[
                ('idEspecificacionProducto', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('precio', models.FloatField()),
                ('precioUnidadMedida', models.FloatField()),
                ('fechaVencimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoBarras', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=70)),
                ('cantidadMedida', models.IntegerField()),
                ('unidadMedida', models.CharField(max_length=10)),
                ('descripcion', models.TextField()),
                ('marca', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='especificacionproducto',
            name='producto',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Producto.Producto'),
        ),
    ]
