# Generated by Django 2.1.5 on 2019-03-21 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Negocio', '0001_initial'),
        ('Producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('nombreCategoria', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('perecedero', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PuntoDeVentaProds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeProducto',
            fields=[
                ('nombreTipo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('metodoAlmacenamiento', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='especificacionproducto',
            name='puntoDeVenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Negocio.PuntoDeVenta'),
        ),
        migrations.AddField(
            model_name='puntodeventaprods',
            name='especificacionProducto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Producto.EspecificacionProducto'),
        ),
        migrations.AddField(
            model_name='puntodeventaprods',
            name='puntoDeVenta',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Negocio.PuntoDeVenta'),
        ),
        migrations.AlterUniqueTogether(
            name='puntodeventaprods',
            unique_together={('puntoDeVenta', 'especificacionProducto')},
        ),
    ]
