# Generated by Django 2.1.7 on 2019-03-22 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0002_auto_20190321_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('especificacionProducto', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Producto.EspecificacionProducto')),
            ],
        ),
    ]
