# Generated by Django 2.1.5 on 2019-03-10 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigoBarras', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=70)),
                ('cantidadMedida', models.IntegerField()),
                ('unidadMedida', models.CharField(max_length=10)),
                ('descripcion', models.TextField()),
                ('marca', models.CharField(max_length=50)),
            ],
        ),
    ]
