# Generated by Django 2.1.7 on 2019-05-17 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('metodoDePago', models.CharField(max_length=30)),
                ('pagado', models.BooleanField()),
                ('usuario', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especificacionProducto', models.CharField(max_length=256)),
                ('cantidad', models.IntegerField()),
                ('factura', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Venta.Factura')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='venta',
            unique_together={('especificacionProducto', 'factura')},
        ),
    ]
