# Generated by Django 2.1.5 on 2019-03-21 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Producto', '0002_auto_20190321_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('metodoDePago', models.CharField(max_length=30)),
                ('pagado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('especificacionProducto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Producto.EspecificacionProducto')),
                ('factura', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Venta.Factura')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='venta',
            unique_together={('especificacionProducto', 'factura')},
        ),
    ]
