# Generated by Django 2.1.7 on 2019-05-18 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Venta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='factura',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Venta.Factura'),
        ),
    ]
