# Generated by Django 2.1.7 on 2019-05-18 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Venta', '0002_auto_20190517_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='pago',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
